concurrency_grid:
  - 1
  - 2
data_root: /datasets
datasets:
  - dim: 384
    n_queries: 1000
    n_vectors: 10000
    name: msmarco-mini-10k-d384
  - dim: 768
    n_queries: 1000
    n_vectors: 50000
    name: cohere-mini-50k-d768
  - dim: 1536
    n_queries: 1000
    n_vectors: 10000
    name: openai-ada-10k-d1536

# HNSW index parameters
indexes:
  qdrant:
    hnsw:
      build:
        ef_construct: 200
        m: 16
      metric: Cosine
      on_disk: true
  weaviate:
    hnsw:
      build:
        efConstruction: 200
        maxConnections: 16
      metric: cosine

repeats: 5
run_seconds: 10
seed: 42
topk: 10
gt_queries_for_recall: 128
